const EMAIL_IS_EMPTY = 'EMAIL_IS_EMPTY';
const PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY';
const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 = 'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8';
const WRONG_PASSWORD = 'WRONG_PASSWORD';
const SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG';
const USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY';
const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
const TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY';
const EMAIL_IS_IN_WRONG_FORMAT = 'EMAIL_IS_IN_WRONG_FORMAT';
const REGISTERED_OKAY = 'REGISTERED_OKAY';
const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
const LEAGUE_ALREADY_EXISTS = 'LEAGUE_ALREADY_EXISTS';
const FORM_ERRORS = 'FORM_ERRORS';
const EXPECTED_INT = 'EXPECTED_INT';
const LEAGUE_SUCCESSFULLY_DELETED = 'LEAGUE_SUCCESSFULLY_DELETED';
const EVENT_LINEUP_SIZE_IS_MISSING = 'EVENT_LINEUP_SIZE_IS_MISSING';
const EVENT_COUNT_SIZE_IS_MISSING = 'EVENT_COUNT_SIZE_IS_MISSING';
const ROSTER_SIZE_IS_MISSING = 'ROSTER_SIZE_IS_MISSING';
const ROSTER_SIZE_TOO_SMALL = 'ROSTER_SIZE_TOO_SMALL';
const ROSTER_SIZE_TOO_BIG = 'ROSTER_SIZE_TOO_BIG';
const EVENT_LINEUP_SIZE_TOO_SMALL = 'EVENT_LINEUP_SIZE_TOO_SMALL';
const EVENT_LINEUP_SIZE_TOO_BIG = 'EVENT_LINEUP_SIZE_TOO_BIG';
const EVENT_LINEUP_COUNT_SIZE_TOO_SMALL = 'EVENT_LINEUP_COUNT_SIZE_TOO_SMALL';
const EVENT_LINEUP_COUNT_SIZE_TOO_BIG = 'EVENT_LINEUP_COUNT_SIZE_TOO_BIG';
const PASSWORD_LENGTH_MUST_BE_LESS_THAN_100 = 'PASSWORD_LENGTH_MUST_BE_LESS_THAN_100';
const NAME_IS_MISSING = 'NAME_IS_MISSING';
const NAME_TOO_SHORT = 'NAME_TOO_SHORT';
const NAME_TOO_LONG = 'NAME_TOO_LONG';
const NOT_INVITED = 'NOT_INVITED';
const ALREADY_INVITED = 'ALREADY_INVITED';
const ALREADY_IN_LEAGUE = 'ALREADY_IN_LEAGUE';
const NO_LEAGUES_FOUND = 'NO_LEAGUES_FOUND';
const NO_LEAGUE_FOUND = 'NO_LEAGUE_FOUND';
const PERMISSION_DENIED = 'PERMISSION_DENIED';
const INVITE_SUCCESSFULLY_SENT = 'INVITE_SUCCESSFULLY_SENT';
const REQUEST_SUCCESSFULLY_SENT = 'REQUEST_SUCCESSFULLY_SENT';
const REQUEST_ALREADY_SENT = 'REQUEST_ALREADY_SENT';
const REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND';
const REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';
const LEAGUE_NOT_PUBLIC = 'LEAGUE_NOT_PUBLIC';
const INVALID_TOKEN = 'INVALID_TOKEN';
const NO_TOKEN_PROVIDED = 'NO_TOKEN_PROVIDED';
const AUTHENTICATED = 'AUTHENTICATED';
const LOGGED_OUT = 'LOGGED_OUT';

const MIN_ROSTER_SIZE = 3;
const MAX_ROSTER_SIZE = 30;

const MIN_EVENT_LINEUP_SIZE = 3;
const MAX_EVENT_LINEUP_SIZE = 30;

const MIN_EVENT_COUNT_SIZE = 3;
const MAX_EVENT_COUNT_SIZE = 30;

module.exports = {
    EMAIL_IS_EMPTY: EMAIL_IS_EMPTY,
    PASSWORD_IS_EMPTY: PASSWORD_IS_EMPTY,
    PASSWORD_LENGTH_MUST_BE_MORE_THAN_8: PASSWORD_LENGTH_MUST_BE_MORE_THAN_8,
    WRONG_PASSWORD: WRONG_PASSWORD,
    SOME_THING_WENT_WRONG: SOME_THING_WENT_WRONG,
    USER_EXISTS_ALREADY: USER_EXISTS_ALREADY,
    USER_DOES_NOT_EXIST: USER_DOES_NOT_EXIST,
    TOKEN_IS_EMPTY: TOKEN_IS_EMPTY,
    EMAIL_IS_IN_WRONG_FORMAT: EMAIL_IS_IN_WRONG_FORMAT,
    NAME_IS_MISSING: NAME_IS_MISSING,
    NAME_TOO_SHORT: NAME_TOO_SHORT,
    NAME_TOO_LONG: NAME_TOO_LONG,
    REGISTERED_OKAY: REGISTERED_OKAY,
    EMAIL_NOT_FOUND: EMAIL_NOT_FOUND,
    LEAGUE_ALREADY_EXISTS: LEAGUE_ALREADY_EXISTS,
    FORM_ERRORS: FORM_ERRORS,
    LEAGUE_SUCCESSFULLY_DELETED: LEAGUE_SUCCESSFULLY_DELETED,
    ROSTER_SIZE_IS_MISSING: ROSTER_SIZE_IS_MISSING,
    EVENT_LINEUP_SIZE_IS_MISSING: EVENT_LINEUP_SIZE_IS_MISSING,
    EVENT_COUNT_SIZE_IS_MISSING: EVENT_COUNT_SIZE_IS_MISSING,
    EXPECTED_INT: EXPECTED_INT,
    MIN_ROSTER_SIZE: MIN_ROSTER_SIZE,
    MAX_ROSTER_SIZE: MAX_ROSTER_SIZE,
    MIN_EVENT_LINEUP_SIZE: MIN_EVENT_LINEUP_SIZE,
    MAX_EVENT_LINEUP_SIZE: MAX_EVENT_LINEUP_SIZE,
    MIN_EVENT_COUNT_SIZE: MIN_EVENT_COUNT_SIZE,
    MAX_EVENT_COUNT_SIZE: MAX_EVENT_COUNT_SIZE,
    ROSTER_SIZE_TOO_SMALL: ROSTER_SIZE_TOO_SMALL,
    ROSTER_SIZE_TOO_BIG: ROSTER_SIZE_TOO_BIG,
    EVENT_LINEUP_SIZE_TOO_SMALL: EVENT_LINEUP_SIZE_TOO_SMALL,
    EVENT_LINEUP_SIZE_TOO_BIG: EVENT_LINEUP_SIZE_TOO_BIG,
    EVENT_LINEUP_COUNT_SIZE_TOO_SMALL: EVENT_LINEUP_COUNT_SIZE_TOO_SMALL,
    EVENT_LINEUP_COUNT_SIZE_TOO_BIG: EVENT_LINEUP_COUNT_SIZE_TOO_BIG,
    PASSWORD_LENGTH_MUST_BE_LESS_THAN_100: PASSWORD_LENGTH_MUST_BE_LESS_THAN_100,
    NOT_INVITED: NOT_INVITED,
    ALREADY_INVITED: ALREADY_INVITED,
    ALREADY_IN_LEAGUE: ALREADY_IN_LEAGUE,
    NO_LEAGUES_FOUND: NO_LEAGUES_FOUND,
    NO_LEAGUE_FOUND: NO_LEAGUE_FOUND,
    PERMISSION_DENIED: PERMISSION_DENIED,
    INVITE_SUCCESSFULLY_SENT: INVITE_SUCCESSFULLY_SENT,
    REQUEST_SUCCESSFULLY_SENT: REQUEST_SUCCESSFULLY_SENT,
    REQUEST_ALREADY_SENT: REQUEST_ALREADY_SENT,
    REQUEST_NOT_FOUND: REQUEST_NOT_FOUND,
    REQUEST_ACCEPTED: REQUEST_ACCEPTED,
    LEAGUE_NOT_PUBLIC: LEAGUE_NOT_PUBLIC,
    INVALID_TOKEN: INVALID_TOKEN,
    NO_TOKEN_PROVIDED: NO_TOKEN_PROVIDED,
    AUTHENTICATED: AUTHENTICATED,
    LOGGED_OUT: LOGGED_OUT
};